### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ntcho** [autarch/autarch#2]
Hi! I loved your profile and the tool you made.

```markdown
See the [houseabsolute org](/houseabsolute) organization for the bulk of my
code. Putting it in an org makes it easier to collaborate with others.
```

The organization link seems to be broken, maybe you can add `https://github.com` in front of the link to fit it. 🙂

**Comment by autarch** [comment]
Thanks for reporting this! It should be fixed in a few minutes when the profile is regenerated.
